data:
  stopword: "/stopwords/common"
  traffic:
    name: "交通肇事罪"
    keyword: "/keyword/traffic/words"
    bagword: "/keyword/traffic/bagwords"
    idf: "/keyword/traffic/idf"
    config: "/config/traffic.yml"
    topk: "20"
    topks: "100"
    fdx1:
      1: "0-36"
      2: "36-120"
      3: "120-180"
    fdx2:
      1: "0-12"
      2: "12-18"
      3: "18-30"
      4: "30-36"
      5: "36-42"
      6: "42-48"
      7: "48-54"
      8: "54-60"
      9: "60-78"
      10: "78-120"
      11: "120-180"
  steal:
    name: "盗窃罪"
    keyword: "/keyword/steal/words"
    bagword: "/keyword/steal/bagwords"
    idf: "/keyword/steal/idf"
    config: "/config/steal.yml"
    topk: "20"
    topks: "100"
    fdx1:
      1: "0-36"
      2: "36-120"
      3: "120-180"
    fdx2:
      1: "0-12"
      2: "12-18"
      3: "18-30"
      4: "30-36"
      5: "36-42"
      6: "42-48"
      7: "48-54"
      8: "54-60"
      9: "60-78"
      10: "78-120"
      11: "120-180"
  robbery:
    name: "抢劫罪"
    keyword: "/keyword/robbery/words"
    bagword: "/keyword/robbery/bagwords"
    idf: "/keyword/robbery/idf"
    config: "/config/robbery.yml"
    topk: "20"
    topks: "100"
    fdx1:
      1: "0-36"
      2: "36-120"
      3: "120-180"
    fdx2:
      1: "0-12"
      2: "12-18"
      3: "18-30"
      4: "30-36"
      5: "36-42"
      6: "42-48"
      7: "48-54"
      8: "54-60"
      9: "60-78"
      10: "78-120"
      11: "120-180"
storeEs:
  thread: "5"
  ip: "192.168.10.104"
  port: "9301"
  cluster: "my-application"
  esindex: "ott_robbery"
  estype: "ott_type"
  estruc: "/store/index.yml"
plugservice:
  model:
    ip: "http://192.168.24.75:5000"
    predictcasecausermdl: "/model/predict/casecause"
  caseportrait:
    ip: "http://123.124.130.22:8762"
    docsplitraw: "/document/split/raw"
    docsplit: "/document/split"
    docportray: "/document/portrait"
    basicinfo: "/predict/basicInfo"
  fdx:
    ip: "http://127.0.0.1:8000"
    fdx1: "/pred/fdx"
    fdx2: "/pred/fdxslim"
