steal:
  type: "dnn-tfidf"
  inhome:
     name: "入户盗窃"
     code: "1001"
     path: "/model/steal/inhome"
  withweapon:
    name: "携带凶器盗窃"
    code: "1002"
    path: "/model/steal/withweapon"
  inhospital:
     name: "在医院盗窃"
     code: "1003"
     path: "/model/steal/inhospital"
  pickpocket:
    name: "扒窃"
    code: "1004"
    path: "/model/steal/pickpocket"
  stealfamily:
    name: "盗窃家庭成员或近亲属财物的"
    code: "1011"
    path: "/model/steal/stealfamily"
  moneysimple:
    name: "盗窃金额"
    code: "1011"
    path: "/model/steal/moneysimple"
robbery:
  type: "dnn-tfidf"
  inhome:
    name: "入户抢劫"
    code: "1001"
    path: "/model/robbery/inhome"
  moneysimple:
    name: "抢劫金额"
    code: "1017"
    path: "/model/robbery/moneysimple"
  withweapon:
    name: "携带凶器或以凶器相威胁"
    code: "1016"
    path: "/model/robbery/withweapon"
seizing:
  type: "dnn-tfidf"
  moneysimple:
    name: "抢夺金额"
    code: "1037"
    path: "/model/seizing/moneysimple"