robbery:
  retainSyntext:
  removeSyntext: "(m|nr)"
  retainWord:
    - "数额较大@1|数额巨大@10|数额特别巨大@10"
    - "入户@2|房内@2|房间@2|家@2|家中@2|家里@2|屋里@2|屋内@2|住处@2|院内@2|室内@2|卧室@2|房间@2|房里@2|客厅@2|撬门入室@|撬门进入@|撞门入内@|[翻爬钻@]入室@|撬开防盗门@2|不在家@2|家中无人@2|家无人@2|无人@2"
    - "凶器@5|刀@5|管制刀具@5|刀具@5|匕首@5|弓@5|弩@5|毒针@5|斧@5|铁剪@3|液压钳@3|撬棒@3"
    - "医院@5|病室@5|住院部@5|卫生院@5|中医会馆@5|病房@5|保健院@5|病床@5|卫生服务中心@5|急诊室@5|医大@5|门诊@5|血液科@5|住院@5|重症监护室@5|神经外科走廊@5|骨科@5|内科诊室@5"
    - "主动@5|返还@5|还给@5|放回@5"
    - "淫秽物品@10|@罂粟@10|红豆杉树@10|毒品@10"
    - "孙媳妇@10|孙女婿@10|侄媳@10|侄女婿@10|外甥@10|外甥女@10|岳父@10|岳母@10|小舅子@10|外祖母@10|外祖夫@10|姥姥@10|女朋友@10|男朋友@10|叔叔@10|其父@10|其母@10|舅舅@10|舅妈@10|姨父@10|姨@10|哥@10|姐@10|其妹@10|其弟@10"
    - "继父@10|姨夫@10|堂弟@10|堂妹@10|堂姐@10|爷爷@10|奶奶@10|继母@10|姑@10|姑父@10"
    - "商业秘密@10|技术成果@10"
    - "破坏@3|砸坏@3|剪短@3|撬锁@#|撬开@3"
    - "行政处罚@5|刑事处罚@5"
    - "持枪@20|仿真枪@20"
    - "公交车@5|公共汽车@5|火车@5|船@5|飞机@5|高铁@5|列车@5|班车@5|客车@5|大巴@5|中巴@5|小巴@5|巴士@5|公共场所@10|游戏厅@5|游侠室@5|营业厅@5|营业室@5|公交站@5|饭馆@3|候车室内@5"
    - "机场@5|地铁@5|强奸@20|性关系@20|诈骗@10|盗窃@5|死亡@10|伤@1|重伤@10|轻伤@5|轻微伤@5|伤残@5"
    - "参与@5|结伙@5|伙同@5|相约@5"
    - "妇女@5|儿童@5|老年人@5|老人@5|弱势群体@5|弱势人员@5|残疾人@5"
    - "累犯@10|前科@10|主犯@10|从犯@10|自首@10|坦白@10|如实供述@10|当庭自愿认罪@10|未成年人@10|老年人@10|孤寡老人@10|未遂@10|中止@10|悔罪@5"
    - "共同犯罪@10|积极赔偿@10|多次@20"
  removeWord: "(省|市|区|县|村|区)"