convertlabel:
  selfsentence:
     share: "/configurecenter/covertlabel/selfsentence/share.yml"
     affray: "/configurecenter/covertlabel/selfsentence/affray.yml"
     concealci: "/configurecenter/covertlabel/selfsentence/concealci.yml"
     drug: "/configurecenter/covertlabel/selfsentence/drug.yml"
     dutyencroachment: "/configurecenter/covertlabel/selfsentence/dutyencroachment.yml"
     endangerpa: "/configurecenter/covertlabel/selfsentence/endangerpa.yml"
     extortion: "/configurecenter/covertlabel/selfsentence/extortion.yml"
     illegaldetension: "/configurecenter/covertlabel/selfsentence/illegaldetension.yml"
     findtrouble: "/configurecenter/covertlabel/selfsentence/findtrouble.yml"
     fraud: "/configurecenter/covertlabel/selfsentence/fraud.yml"
     injury: "/configurecenter/covertlabel/selfsentence/injury.yml"
     rape: "/configurecenter/covertlabel/selfsentence/rape.yml"
     robbery: "/configurecenter/covertlabel/selfsentence/robbery.yml"
     seizing: "/configurecenter/covertlabel/selfsentence/seizing.yml"
     steal: "/configurecenter/covertlabel/selfsentence/steal.yml"
     traffic: "/configurecenter/covertlabel/selfsentence/traffic.yml"
  leianv1:
    traffic: "/configurecenter/covertlabel/leian/traffic.yml"
    share: "/configurecenter/covertlabel/leian/share.yml"
    injury: "/configurecenter/covertlabel/leian/injury.yml"
    rape: "/configurecenter/covertlabel/leian/rape.yml"
    illegaldetension: "/configurecenter/covertlabel/leian/illegaldetension.yml"
    steal: "/configurecenter/covertlabel/leian/steal.yml"
    robbery: "/configurecenter/covertlabel/leian/robbery.yml"
    fraud: "/configurecenter/covertlabel/leian/fraud.yml"
    seizing: "/configurecenter/covertlabel/leian/seizing.yml"
    dutyencroachment: "/configurecenter/covertlabel/leian/dutyencroachment.yml"
    extortion: "/configurecenter/covertlabel/leian/extortion.yml"
    endangerpa: "/configurecenter/covertlabel/leian/endangerpa.yml"
    affray: "/configurecenter/covertlabel/leian/affray.yml"
    findtrouble: "/configurecenter/covertlabel/leian/findtrouble.yml"
    concealci: "/configurecenter/covertlabel/leian/concealci.yml"
    drug: "/configurecenter/covertlabel/leian/drug.yml"
checklabel:
  sentence: "configurecenter/sentence/checklabel/sentence.yml"
lxfeature:
  common: "/configurecenter/common/common.yml"
  money: "/configurecenter/common/money.yml"
  gram: "/configurecenter/common/gram.yml"
  courtdecision: "/configurecenter/sentence/courtdecision.yml"
  share: "/extractor/feature/share.yml"
  traffic: "/extractor/feature/traffic.yml"
  injury: "/extractor/feature/injury.yml"
  rape: "/extractor/feature/rape.yml"
  steal: "/extractor/feature/steal.yml"
  affray: "/extractor/feature/affray.yml"
  concealci: "/extractor/feature/concealci.yml"
  drug: "/extractor/feature/drug.yml"
  dutyencroachment: "/extractor/feature/dutyencroachment.yml"
  endangerpa: "/extractor/feature/endangerpa.yml"
  extortion: "/extractor/feature/extortion.yml"
  illegaldetension: "/extractor/feature/illegaldetension.yml"
  fraud: "/extractor/feature/fraud.yml"
  robbery: "/extractor/feature/robbery.yml"
  findtrouble: "/extractor/feature/findtrouble.yml"
  seizing: "/extractor/feature/seizing.yml"
  invalidCreditCardFraud: "/extractor/feature/useinvalidcreditcardfraud.yml"
  fraudulentIdentificationFraud: "/extractor/feature/usefraudulentidentificationobtainedcreditcardfraud.yml"
  counterfeitCreditCardFraud: "/extractor/feature/usecounterfeitcreditcardfraud.yml"
  maliciousOverDraftFraud: "/extractor/feature/maliciousoverdraftfraud.yml"
  illegalPossessionDrugs: "/extractor/feature/illegalpossessionofdrugs.yml"
  prostitution: "/extractor/feature/prostitution.yml"
  providingVenuesForDrugUsers: "/extractor/feature/providingvenuesfordrugusers.yml"
  individualContractFraud: "/extractor/feature/individualcontractfraud.yml"
  companyContractFraud: "/extractor/feature/companycontractfraud.yml"
  individualFundRaisingFraud: "/extractor/feature/individualfundraisingfraud.yml"
  companyFundRaisingFraud: "/extractor/feature/companyfundraisingfraud.yml"
  companyIllegallyAbsorbingPublicDeposits: "/extractor/feature/companyillegallyabsorbingpublicdeposits.yml"
  individualIllegallyAbsorbingPublicDeposits: "/extractor/feature/individualillegallyabsorbingpublicdeposits.yml"
  drunkDriving: "/extractor/feature/drunkDriving.yml"
  chaseRace: "/extractor/feature/chaseRace.yml"
  schoolBusBusinessOrPassengerTransportation: "/extractor/feature/schoolBusBusinessOrPassengerTransportation.yml"
  transportationOfHazardousChemical: "/extractor/feature/transportationOfHazardousChemical.yml"
others:
  time: "/timexp.m"
  interfaceurl: "/interface/interface.yml"
  factsplit: "/split/factsplit.yml"
  casecause: "/extractor/casecause/casecause.yml"
endecrypt:
  encrypt: "true"
  encryptplace:
    lxfeature: "/configurecenter/sentence/feature/"

